# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/elisedonszelmann-lund/DeformViewVisualizer/DeformViewVisualizer/DeformView/Resources/UI/DeformView.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DeformView(object):
    def setupUi(self, DeformView):
        DeformView.setObjectName("DeformView")
        DeformView.resize(586, 575)
        self.formLayout = QtWidgets.QFormLayout(DeformView)
        self.formLayout.setContentsMargins(-1, 0, -1, -1)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(DeformView)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_2)
        self.referenceVolume = qMRMLNodeComboBox(DeformView)
        self.referenceVolume.setNodeTypes(['vtkMRMLScalarVolumeNode'])
        self.referenceVolume.setShowChildNodeTypes(False)
        self.referenceVolume.setNoneEnabled(True)
        self.referenceVolume.setAddEnabled(True)
        self.referenceVolume.setRemoveEnabled(True)
        self.referenceVolume.setObjectName("referenceVolume")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.referenceVolume)
        self.label_6 = QtWidgets.QLabel(DeformView)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.label_6)
        self.backgroundVolume = qMRMLNodeComboBox(DeformView)
        self.backgroundVolume.setNodeTypes([])
        self.backgroundVolume.setHideChildNodeTypes([])
        self.backgroundVolume.setInteractionNodeSingletonTag("")
        self.backgroundVolume.setObjectName("backgroundVolume")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.backgroundVolume)
        self.label = QtWidgets.QLabel(DeformView)
        self.label.setObjectName("label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label)
        self.transformNode = qMRMLNodeComboBox(DeformView)
        self.transformNode.setNodeTypes([])
        self.transformNode.setHideChildNodeTypes([])
        self.transformNode.setInteractionNodeSingletonTag("")
        self.transformNode.setObjectName("transformNode")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.transformNode)
        self.label_3 = QtWidgets.QLabel(DeformView)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.displacementMagnitudeVolume = qMRMLCheckableNodeComboBox(DeformView)
        self.displacementMagnitudeVolume.setAddEnabled(True)
        self.displacementMagnitudeVolume.setRenameEnabled(True)
        self.displacementMagnitudeVolume.setObjectName("displacementMagnitudeVolume")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.displacementMagnitudeVolume)
        self.applyButton = QtWidgets.QPushButton(DeformView)
        self.applyButton.setEnabled(False)
        self.applyButton.setObjectName("applyButton")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.applyButton)
        self.label_4 = QtWidgets.QLabel(DeformView)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.existingDisplacementVolumeSelector = qMRMLCheckableNodeComboBox(DeformView)
        self.existingDisplacementVolumeSelector.setObjectName("existingDisplacementVolumeSelector")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.SpanningRole, self.existingDisplacementVolumeSelector)
        self.loadDisplacementVolumeButton = QtWidgets.QPushButton(DeformView)
        self.loadDisplacementVolumeButton.setObjectName("loadDisplacementVolumeButton")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.SpanningRole, self.loadDisplacementVolumeButton)
        self.label_5 = QtWidgets.QLabel(DeformView)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.colorMapSelector = qMRMLColorTableComboBox(DeformView)
        self.colorMapSelector.setObjectName("colorMapSelector")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.colorMapSelector)
        self.enableHoverDisplayCheckbox = ctkCheckBox(DeformView)
        self.enableHoverDisplayCheckbox.setObjectName("enableHoverDisplayCheckbox")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.enableHoverDisplayCheckbox)
        self.label_7 = QtWidgets.QLabel(DeformView)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.thresholdMaxSpinBox = QtWidgets.QDoubleSpinBox(DeformView)
        self.thresholdMaxSpinBox.setObjectName("thresholdMaxSpinBox")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.thresholdMaxSpinBox)
        self.thresholdMinSpinBox = QtWidgets.QDoubleSpinBox(DeformView)
        self.thresholdMinSpinBox.setSingleStep(0.5)
        self.thresholdMinSpinBox.setObjectName("thresholdMinSpinBox")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.thresholdMinSpinBox)
        self.thresholdSlider = ctkDoubleRangeSlider(DeformView)
        self.thresholdSlider.setMaximum(50.0)
        self.thresholdSlider.setSingleStep(0.5)
        self.thresholdSlider.setMaximumValue(10.0)
        self.thresholdSlider.setOrientation(QtCore.Qt.Horizontal)
        self.thresholdSlider.setObjectName("thresholdSlider")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.FieldRole, self.thresholdSlider)
        self.label_8 = QtWidgets.QLabel(DeformView)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.LabelRole, self.label_8)

        self.retranslateUi(DeformView)
        QtCore.QMetaObject.connectSlotsByName(DeformView)

    def retranslateUi(self, DeformView):
        _translate = QtCore.QCoreApplication.translate
        self.label_2.setText(_translate("DeformView", "Mapping Image:"))
        self.referenceVolume.setToolTip(_translate("DeformView", "Pick the output to the algorithm."))
        self.referenceVolume.setProperty("SlicerParameterName", _translate("DeformView", "referenceVolume"))
        self.label_6.setText(_translate("DeformView", "Background Image:"))
        self.label.setText(_translate("DeformView", "Transformation:"))
        self.transformNode.setProperty("SlicerParameterName", _translate("DeformView", "transformNode"))
        self.label_3.setText(_translate("DeformView", "Output Volume:"))
        self.applyButton.setToolTip(_translate("DeformView", "Run the algorithm."))
        self.applyButton.setText(_translate("DeformView", "Compute Mapping"))
        self.label_4.setText(_translate("DeformView", "Load Volume:"))
        self.loadDisplacementVolumeButton.setText(_translate("DeformView", "Load Volume"))
        self.label_5.setText(_translate("DeformView", "Color Map:"))
        self.label_7.setText(_translate("DeformView", "Enable Mouse mm DIsplay"))
        self.label_8.setText(_translate("DeformView", "Threshold Slider:"))
from ctkCheckBox import ctkCheckBox
from qMRMLCheckableNodeComboBox import qMRMLCheckableNodeComboBox
from qMRMLColorTableComboBox import qMRMLColorTableComboBox
from qMRMLNodeComboBox import qMRMLNodeComboBox
from qMRMLWidget import qMRMLWidget
